version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db1
    restart: always
    environment:
      POSTGRES_USER: ykmsh
      POSTGRES_PASSWORD: pickMe5684321
      POSTGRES_DB: pickme
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: